language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash ./push.sh
 
 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
 
